name: CI
on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: D Compiler Installation
      uses: dlang-community/setup-dlang@v1.3.0         
    - name: Build
      run: dub build
    - name: Tests
      run: dub test
